In [8]:
#ml basics
#create array
# from numpy import array #import array() function
import numpy as np 
l = [1.0, 2.0, 4.0]
l1 = np.array(l)
print(l1) #print array
print(l1.shape) #print array shape
print(l1.dtype) #print array datatype

[1. 2. 4.]
(3,)
float64


In [ ]:
***The empty() function will create a new array of the specified shape.
***The argument to the function is an array or tuple that species the
length of each dimension of the array to create.
***The values or content of the created array will be random and will
need to be assigned before use.

In [9]:
l2 = np.empty([3,3]) #create an empty array
print(l2)

[[4.64488820e-310 1.01777523e-321 4.64488834e-310]
 [3.95252517e-323 1.97626258e-323 4.64488653e-310]
 [4.64488653e-310 4.64488653e-310 4.64488653e-310]]
