In [ ]:
**The arithmetic mean can be calculated for a vector or matrix in NumPy by
using the mean() function
**Formula
**Mean = P(x) * ∑x

In [6]:
#let's dive into probs
#mean  numpy
import numpy as np 

arr = np.array([1,2,3,4,5,6])
print(arr, "\n")
print(np.mean(arr))

[1 2 3 4 5 6] 

3.5


In [11]:
arr1 = np.array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
print(arr1, "\n")

col_mean = np.mean(arr1, axis=0) #column mean
print(col_mean, "\n")

row_mean = np.mean(arr1, axis=1) #row mean
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] 

[1. 2. 3. 4. 5. 6.] 

[3.5 3.5]
