In [ ]:
**The arithmetic mean can be calculated for a vector or matrix in NumPy by
using the mean() function
**Formula
**Mean = P(x) * ∑x

In [15]:
#let's dive into probs
#mean  numpy
import numpy as np 

arr = np.array([1,2,3,4,5,6])
print(arr, "\n")
print(np.mean(arr))

var = np.var(arr, ddof=1)
print(var)

[1 2 3 4 5 6] 

3.5
3.5


In [18]:
arr1 = np.array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
print(arr1, "\n")

col_mean = np.mean(arr1, axis=0) #column mean
print(col_mean, "\n")

row_mean = np.mean(arr1, axis=1) #row mean
print(row_mean, "\n")

# std deviation
col_std = np.std(arr, ddof=1, axis=0)
print(col_std, "\n")

row_std = np.std(arr, ddof=1, axis=0)
print(row_std)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] 

[1. 2. 3. 4. 5. 6.] 

[3.5 3.5] 

1.8708286933869707 

1.8708286933869707


In [24]:
x = np.array([1,2,3,4,5,6])
print(x, "\n")

y = np.array([6,5,4,3,2,1])
print(y, "\n")

cov = np.cov(x,y)[0,1]
print(cov)

[1 2 3 4 5 6] 

[6 5 4 3 2 1] 

-3.5
